spring:
  cloud:
    gateway:
      routes:
        - id: security-service
          uri: http://localhost:8082
          predicates:
            - Path=/api/security/**
          filters:
            - AuthenticationFilter
        - id: management-service
          uri: http://localhost:8083
          predicates:
            - Path=/api/test/**
          filters:
            - AuthenticationFilter
        - id: registration-service
          uri: http://localhost:8084
          predicates:
            - Path=/api/registration/**
          filters:
            - AuthenticationFilter
